format = """
[î‚¶](#003444)\
$username\
[î‚°](bg:#268BD3 fg:#003444)\
$directory\
[î‚°](fg:#268BD3 bg:#7F9403)\
$git_branch\
$git_status\
[î‚°](fg:#7F9403 bg:#DADDE2)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$dotnet\
$julia\
$nodejs\
$nim\
$rust\
[î‚°](fg:#DADDE2 bg:#2AA198)\
$docker_context\
[î‚°](fg:#2AA198 bg:#33658A)\
$time\
[î‚° ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#003444"
style_root = "bg:#003444"
format = '[$user ]($style)'

[directory]
style = "bg:#268BD3"
format = "[ $path ](#072E3D $style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜ "
style = "bg:#2AA198"
format = '[[ $symbol ($version) ](bg:#2AA198)]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#2AA198"
format = '[[ $symbol $context ](bg:#2AA198)]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#2AA198"
format = '[[ $symbol ($version) ](bg:#2AA198)]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#2AA198"
format = '[[ $symbol ($version) ](bg:#2AA198)]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#7F9403"
format = '[[ $symbol $branch ](#072E3D bg:#7F9403)]($style)'

[git_status]
style = "bg:#7F9403"
format = '[[($all_status$ahead_behind )](#072E3D bg:#7F9403)]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#2AA198"
format = '[[ $symbol ($version) ](bg:#2AA198)]($style)'

[haskell]
symbol = "î· "
style = "bg:#2AA198"
format = '[[ $symbol ($version) ](bg:#2AA198)]($style)'

[java]
symbol = "î‰– "
style = "bg:#2AA198"
format = '[[ $symbol ($version) ](bg:#2AA198)]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#2AA198"
format = '[[ $symbol ($version) ](bg:#2AA198)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#2AA198"
format = '[[ $symbol ($version) ](bg:#2AA198)]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#2AA198"
format = '[[ $symbol ($version) ](bg:#2AA198)]($style)'

[rust]
symbol = "ğŸ¦€ "
style = "bg:#2AA198"
format = '[[ $symbol ($version) ](bg:#2AA198)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ â™¥ $time ](bg:#33658A)]($style)'

[dotnet]
symbol = "ğŸ¦Š "
style = "green"
format = "[[$symbol ($version) ](bg:#2AA198)]($style)"